apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/managed-by: argocd
  annotations:
    description: Qdrant Helm deployment
spec:
  project: default
  source:
    repoURL: https://qdrant.github.io/qdrant-helm
    chart: qdrant
    targetRevision: v1.17.1
    helm:
      values: |
        replicaCount: 1
        image:
          repository: docker.io/qdrant/qdrant
          tag: v1.17.1
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
        persistence:
          enabled: true
          size: 20Gi
          accessModes:
          - ReadWriteOnce
        resources:
          requests:
            cpu: '500m'
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1Gi
        config:
          cluster:
            enabled: true
            p2p:
              port: 6335
              enable_tls: false
            consensus:
              tick_period_ms: 100
          service:
            enable_tls: false
          log_level: INFO
          on_disk_payload: false
        updateVolumeFsOwnership: true
        podManagementPolicy: Parallel
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - '3'
        podAnnotations:
          app.kubernetes.io/managed-by: argocd
          qdrant.argoproj.io/config-checksum: a2db7b7344a558d8db621b7eaf8bfbdf4f45fd04ae27bd7833d3729da18ead88
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/versions
  - group: ''
    kind: ConfigMap
    jsonPointers:
    - /data