apiVersion: v1
kind: Service
metadata:
  name: dense-svc
  namespace: inference
  labels:
    app.kubernetes.io/name: dense
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dense
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP