apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: inference
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: tunnel-config
data:
  config.yaml: |
    tunnel: tabular-api-tunnel
    ingress:
    - hostname: auth.athithya.site
      service: http://auth-svc.inference.svc.cluster.local:80
    - hostname: predict.athithya.site
      service: http://tabular-inference-serve-svc.inference.svc.cluster.local:8000
    - service: http_status:404
