apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.5.0
    helm:
      values: |
        installCRDs: true

        serviceAccount:
          create: true

        extraEnv:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: access-key-id

          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: secret-access-key

          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: session-token
                optional: true

          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: region

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true