apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: signoz-clickhouse-credentials
  namespace: signoz
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore

  target:
    name: signoz-clickhouse-credentials
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: admin-password
      remoteRef:
        key: /autonomous-incident-responder/signoz/clickhouse/admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inference-postgres-connection
  namespace: inference
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore

  target:
    name: postgres-connection-pooler
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: connection-string
      remoteRef:
        key: /autonomous-incident-responder/inference/postgres/connection-string-pooler
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tool-server-api-key
  namespace: inference
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore

  target:
    name: tool-server-api-key
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: api-key
      remoteRef:
        key: /autonomous-incident-responder/tool-server/api-key